# Generated by Django 5.0.4 on 2024-05-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serial_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'serial',
            },
        ),
        migrations.CreateModel(
            name='Get_Actior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actior_name', models.CharField(max_length=20)),
                ('yera', models.IntegerField()),
                ('gender', models.CharField(verbose_name=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rasm/')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serial.serial_name')),
            ],
            options={
                'db_table': 'aktior',
            },
        ),
    ]
